### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by jakubvojacek** [mallgroup/roadrunner#10]
Hello @bckp 

is this project up to date and can be used with latest nette? I was going to try it with roadrunner but have failed so far. 

I didnt really give it enough time tho, I just installed it via composer and registered the extension. But I got errors about `http.response` not being registered.

Do you think you could put together few lines of documenatation how to use it please?

Also, will this extension work for both roadrunner and regular php-fpm requests at the same time?

Thanks a lot!

**Comment by bckp** [comment]
We are working on it and even use it in production, but it is still big WIP, so far we have issues with sessions, as nette isnjust not ready for long running process...
Did you use composer version?
I will for sure create some readme how to use this... I will look at it tomorow at work

**Comment by jakubvojacek** [comment]
> Did you use composer version?

Yes, I installed it via composer.

> so far we have issues with sessions, as nette isnjust not ready for long running process...

as long as the application would work at the same time with php-fpm and roadrunner, sesions arent that much of an issue. We got an administration module that has GUI and uses nette session but 99.9999 requests are API calls without sessions. 

Thanks

**Comment by bckp** [comment]
I uploaded some basic howto we run RoadRunner with our app... hope this will helps, i wish to finish the middleware version and then create docs, as middleware version is so much powerfull and fun to play with

**Comment by jakubvojacek** [comment]
Thanks, I was able to make some requests work!

Hopefully you'll have time to finish middlewares :)

Thanks alot!

**Comment by bckp** [comment]
Well, core is working, sessions are issue...
