### ISSUE TITLE
Possibility of restarting worker from within the application

### ISSUE THREAD

**Issue by jakubvojacek** [mallgroup/roadrunner#17]
Hello

I think it would be helpfull to be able to restart worker from within the application (eg when we the connection to database dies and a new one is needed - it might be easier just to kill the worker and let a new one spawn instead of reconnecting)

I think it would be possible via adding new Exception class and catching it here https://github.com/mallgroup/roadrunner/blob/main/src/RoadRunner.php#L77 and then call `$worker->stop()`?

What do you think?

**Comment by bckp** [comment]
Yeah, that should be possible, i will look at this, as right now, we are trying to get middlewares working...

Right now, you should be able to stop process simply by sending EXIT or DIE, RoadRunner should notice this worker is dead and start new one...

**Comment by bckp** [comment]
In new version (middleware one, now in master) you can simply get RoadRunner::stop to stop worker, is this ok for you? :)

**Comment by jakubvojacek** [comment]
yes, thank you :+1:
